CREATE TABLE IF NOT EXISTS item (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO BIGINT,
    DESCRICAO VARCHAR(255),
    QUANTIDADE INTEGER,
    PRECO_TOTAL DECIMAL(10, 2)
);

ALTER TABLE item ALTER COLUMN id RESTART WITH 1;